### ISSUE TITLE
Missing Profile Name from Torque Data

### ISSUE THREAD

**Issue by FuzzyMistborn** [junalmeida/homeassistant-torque#8]
## Describe the bug
Tried setting this up as I'm having issues with the official component.  Have some custom PIDs because I have an EV.  Not sure if that's the cause but the data is getting through but no sensors are created.

## Debug log

```text

This error originated from a custom integration.

Logger: custom_components.torque_logger
Source: custom_components/torque_logger/api.py:241
Integration: Torque Logger (documentation, issues)
First occurred: 9:26:48 PM (19 occurrences)
Last logged: 9:34:00 PM

Missing profile name from torque data.

```

**Comment by junalmeida** [comment]
Torque is supposed to post the profile name at the very first post to your home assistant instance. Unless somehow it has lost this first package, I don't know why it is not sending. If you check `api.py` at line 241 you will see that this only happens if there is no previous session with a profile name. 

What I can ask or suggest is to reboot your torque instance (make sure torque is fully restarted, if not sure restart the device torque is running on).

Then try again.

**Comment by FuzzyMistborn** [comment]
Ahha, it's working now without errors, but no sensors are getting populated.  Seems to be an issue on my end, I'll work on it.  Thanks for the insight!

**Comment by junalmeida** [comment]
Ok, no problem. Also have sure you have selected some sensors on Torque app.
